; Mariner Config Overrides (shared between client and server)

; [OnlineSubsystemSteamFSG]
; AppId=1233550

[MangoClient]
IAMDedicatedServerBasicAuthToken=NGE4MWNmMTg5ZGI3NDFkMDllOTZhYmMyMWZiZjcyM2Q6MDBlODgzNDg5OTlmNGRhMjhkMWJjMGUzNjFhZDE5ZjM=
DevCluster=localhost:5000
CertCluster=localhost:5000
ProdCluster=localhost:5000
BaseUrl-MangoCMSService="https://{Cluster}/cms"
BaseUrl-MangoConfigCDNService="http://{Cluster}"
BaseUrl-MangoIAMService="http://{Cluster}/iam"
BaseUrl-MangoInventoryService="http://{Cluster}/inventory"
BaseUrl-MangoLobbyService="http://{Cluster}/lobby"
BaseUrl-MangoLobbyServiceWebSocket="ws://{Cluster}/lobby"
BaseUrl-MangoMatchmakingService="http://{Cluster}/matchmaking"
BaseUrl-MangoProfileService="http://{Cluster}/profile"
BaseUrl-MangoQuestService="http://{Cluster}/quest"
BaseUrl-MangoRelayService="http://{Cluster}/relay"
BaseUrl-MangoReportingService="http://{Cluster}/reporting"
BaseUrl-MangoTelemetryService="http://{Cluster}/telemetry"

[PinTelemetry]
Test-EndpointUrl="http://localhost:5000/pinEvents"
Prod-EndpointUrl="http://localhost:5000/pinEvents"

[OnlineSubsystemOrigin]
Int-BaseUrl-Accounts="http://localhost:5000"
Int-BaseUrl-Gateway="http://localhost:5000/proxy"
Int-BaseUrl-Friends="http://localhost:5000"
Int-BaseUrl-API="http://localhost:5000"
Prod-BaseUrl-Accounts="http://localhost:5000"
Prod-BaseUrl-Gateway="http://localhost:5000/proxy"
Prod-BaseUrl-Friends="http://localhost:5000"
Prod-BaseUrl-API="http://localhost:5000"
LT-BaseUrl-Accounts="http://localhost:5000"
LT-BaseUrl-Gateway="http://localhost:5000/proxy"
LT-BaseUrl-Friends="http://localhost:5000"
LT-BaseUrl-API="http://localhost:5000"

[RTMClient]
Int-BaseUrl="ws://localhost:5000/websocket"
Prod-BaseUrl="ws://localhost:5000/websocket"

; [VoiceChat.Vivox]
; ServerUrl="--- REPLACE WITH YOUR VIVOX SERVER URL ---"
; Domain="--- REPLACE WITH YOUR VIVOX DOMAIN ---"
; Issuer="--- REPLACE WITH YOUR VIVOX TOKEN ISSUER ---"
