// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenRocketArena.Server.Data;

#nullable disable

namespace OpenRocketArena.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322213405_AddPlayerStats")]
    partial class AddPlayerStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("OpenRocketArena.Server.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.BlastPassProgression", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlastPassId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlastPassLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlastPassXp")
                        .HasColumnType("INTEGER");

                    b.Property<float>("BpProgress")
                        .HasColumnType("REAL");

                    b.Property<int>("PartyXpBonus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Viewed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpBonus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("BlastPassProgressions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.CharacterEmote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterProgressionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmoteType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterProgressionId");

                    b.ToTable("CharacterEmotes");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.CharacterProgression", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPlayedMatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Progress")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("CharacterProgressions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.EquipmentSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterProgressionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterProgressionId");

                    b.ToTable("EquipmentSets");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.EquipmentSetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EquipmentSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentSetId");

                    b.ToTable("EquipmentSetItems");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.IamSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("IamSessions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryBlastPass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmsBlastPassId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryBlastPasses");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryChest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmsChestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryChests");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryDuplicateItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryDuplicateItems");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmsItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PopUpNotification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Viewed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryOneTimeOffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryOneTimeOffers");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryPromotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromotionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryPromotions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.ItemLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Progress")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalXp")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ItemLevels");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.MatchHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchEndJsonData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("MatchHistories");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.MotdView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("MotdViews");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.OAuthSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("OAuthSessions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.Persona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamespaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RocketBucks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RocketParts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("PlayerInventories");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveMatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActiveMatchIdUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdvertState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtifactUnlockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ArtifactUnlockProgress")
                        .HasColumnType("REAL");

                    b.Property<int>("ArtifactUnlockXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BanMock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareerXp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPlayedMatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OnboardingState")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Progress")
                        .HasColumnType("REAL");

                    b.Property<string>("PromosOwned")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UnbanTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerStatEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Max")
                        .HasColumnType("REAL");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Min")
                        .HasColumnType("REAL");

                    b.Property<long>("StatGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Sum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StatGroupId");

                    b.ToTable("PlayerStatEntries");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerStatGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesDrawn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesQuit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SliceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SliceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SliceType", "SliceValue")
                        .IsUnique();

                    b.ToTable("PlayerStatGroups");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlaylistRanking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BotLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesQuit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillMean")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillStdDev")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Streak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PlaylistRankings");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.ProfileEquipItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileEquipItems");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.Quest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlastPassXpReward")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DismissCooldown")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Goal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastDismissTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedRewardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.BlastPassProgression", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("BlastPassLevels")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.CharacterEmote", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.CharacterProgression", "CharacterProgression")
                        .WithMany("Emotes")
                        .HasForeignKey("CharacterProgressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterProgression");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.CharacterProgression", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("CharacterProgressions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.EquipmentSet", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.CharacterProgression", "CharacterProgression")
                        .WithMany("EquipmentSets")
                        .HasForeignKey("CharacterProgressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterProgression");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.EquipmentSetItem", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.EquipmentSet", "EquipmentSet")
                        .WithMany("Items")
                        .HasForeignKey("EquipmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentSet");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.IamSession", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithMany("IamSessions")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryBlastPass", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerInventory", "Inventory")
                        .WithMany("BlastPasses")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryChest", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerInventory", "Inventory")
                        .WithMany("Chests")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryDuplicateItem", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerInventory", "Inventory")
                        .WithMany("DupeItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryItem", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerInventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryOneTimeOffer", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerInventory", "Inventory")
                        .WithMany("OneTimeOffers")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.InventoryPromotion", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerInventory", "Inventory")
                        .WithMany("Promotions")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.ItemLevel", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("ItemLevels")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.MatchHistory", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithMany("MatchHistories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.MotdView", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("MotdViews")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.OAuthSession", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.Persona", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithMany("Personas")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerInventory", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithOne("Inventory")
                        .HasForeignKey("OpenRocketArena.Server.Entities.PlayerInventory", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerProfile", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("OpenRocketArena.Server.Entities.PlayerProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerStatEntry", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerStatGroup", "StatGroup")
                        .WithMany("Stats")
                        .HasForeignKey("StatGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatGroup");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerStatGroup", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("StatGroups")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlaylistRanking", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("PlaylistRankings")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.ProfileEquipItem", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.PlayerProfile", "Profile")
                        .WithMany("Equipment")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.Quest", b =>
                {
                    b.HasOne("OpenRocketArena.Server.Entities.Account", "Account")
                        .WithMany("Quests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.Account", b =>
                {
                    b.Navigation("IamSessions");

                    b.Navigation("Inventory");

                    b.Navigation("MatchHistories");

                    b.Navigation("Personas");

                    b.Navigation("Profile");

                    b.Navigation("Quests");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.CharacterProgression", b =>
                {
                    b.Navigation("Emotes");

                    b.Navigation("EquipmentSets");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.EquipmentSet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerInventory", b =>
                {
                    b.Navigation("BlastPasses");

                    b.Navigation("Chests");

                    b.Navigation("DupeItems");

                    b.Navigation("Items");

                    b.Navigation("OneTimeOffers");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerProfile", b =>
                {
                    b.Navigation("BlastPassLevels");

                    b.Navigation("CharacterProgressions");

                    b.Navigation("Equipment");

                    b.Navigation("ItemLevels");

                    b.Navigation("MotdViews");

                    b.Navigation("PlaylistRankings");

                    b.Navigation("StatGroups");
                });

            modelBuilder.Entity("OpenRocketArena.Server.Entities.PlayerStatGroup", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
